default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DEV_DB'] %>

test:
  <<: *default
  database: <%= ENV['TEST_DB'] %>

production:
  <<: *default
  database: <%= ENV['PROD_DB'] %>
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
